import os, json, joblib, numpy as np, pandas as pd, streamlit as st
BASE=os.path.dirname(os.path.abspath(__file__))
st.set_page_config(page_title="Marketing Campaign Analytics",layout="wide")
st.title("📊 Multi-Brand Marketing Campaign Analytics")
st.caption("Nykaa • Purplle • Tira | EDA, Revenue Prediction and Profit/Loss Classification")
data_path=os.path.join(BASE,"data","processed","combined_cleaned_campaign_data.csv")
if not os.path.exists(data_path):
    st.warning("Run `python src/pipeline.py` first.")
    st.stop()
df=pd.read_csv(data_path)
tab1,tab2,tab3=st.tabs(["Dashboard","Revenue Prediction","Profit/Loss Prediction"])
with tab1:
    st.sidebar.header("Filters")
    brand=st.sidebar.multiselect("Brand",sorted(df.Brand.unique()),default=sorted(df.Brand.unique()))
    d=df[df.Brand.isin(brand)]
    c1,c2,c3,c4=st.columns(4)
    c1.metric("Campaigns",f"{len(d):,}")
    c2.metric("Total Revenue",f"₹{d.Revenue.sum():,.0f}")
    c3.metric("Average ROI",f"{d.ROI.mean():.2f}")
    c4.metric("Profit Rate",f"{d.Profit_Flag.mean()*100:.1f}%")
    st.subheader("Brand Performance")
    st.bar_chart(d.groupby("Brand")[["Revenue","ROI"]].mean())
    st.subheader("Revenue by Campaign Type")
    st.bar_chart(d.groupby("Campaign_Type").Revenue.sum().sort_values(ascending=False))
    st.subheader("Data Preview")
    st.dataframe(d.head(100),use_container_width=True)
with tab2:
    st.header("Revenue Prediction")
    model=joblib.load(os.path.join(BASE,"models","revenue_model.pkl"))
    brands=sorted(df.Brand.unique()); types=sorted(df.Campaign_Type.unique()); audiences=sorted(df.Target_Audience.unique()); langs=sorted(df.Language.unique()); segs=sorted(df.Customer_Segment.unique())
    a,b,c=st.columns(3)
    Brand=a.selectbox("Brand",brands); Campaign_Type=b.selectbox("Campaign Type",types); Target_Audience=c.selectbox("Target Audience",audiences)
    a,b,c=st.columns(3)
    Duration=a.number_input("Duration (days)",1,365,15); Channel_Used=b.text_input("Channels","Facebook, Google"); Language=c.selectbox("Language",langs)
    a,b,c=st.columns(3)
    Impressions=a.number_input("Impressions",0.0,10000000.0,50000.0); Clicks=b.number_input("Clicks",0.0,1000000.0,4000.0); Leads=c.number_input("Leads",0.0,1000000.0,1500.0)
    a,b,c=st.columns(3)
    Conversions=a.number_input("Conversions",0.0,1000000.0,700.0); Acquisition_Cost=b.number_input("Acquisition Cost",0.0,1000000.0,300.0); Engagement_Score=c.number_input("Engagement Score",0.0,100.0,15.0)
    Customer_Segment=st.selectbox("Customer Segment",segs); Month=st.number_input("Month",1,12,6); Year=st.number_input("Year",2020,2035,2025)
    if st.button("Predict Revenue"):
        x=pd.DataFrame([{"Brand":Brand,"Campaign_Type":Campaign_Type,"Target_Audience":Target_Audience,"Duration":Duration,"Channel_Used":Channel_Used,"Impressions":Impressions,"Clicks":Clicks,"Leads":Leads,"Conversions":Conversions,"Acquisition_Cost":Acquisition_Cost,"Language":Language,"Engagement_Score":Engagement_Score,"Customer_Segment":Customer_Segment,"Month":Month,"Year":Year,"Channel_Count":len([z for z in Channel_Used.split(",") if z.strip()])}])
        st.success(f"Predicted Revenue: ₹{model.predict(x)[0]:,.2f}")
with tab3:
    st.header("Profit/Loss Prediction")
    model=joblib.load(os.path.join(BASE,"models","profit_loss_model.pkl"))
    st.info("ROI is not directly entered because it is excluded from classification features.")
    a,b,c=st.columns(3)
    Brand=a.selectbox("Brand",sorted(df.Brand.unique()),key="pbrand"); Campaign_Type=b.selectbox("Campaign Type",sorted(df.Campaign_Type.unique()),key="ptype"); Target_Audience=c.selectbox("Target Audience",sorted(df.Target_Audience.unique()),key="paud")
    a,b,c=st.columns(3)
    Duration=a.number_input("Duration",1,365,15,key="pdur"); Channel_Used=b.text_input("Channels", "Facebook, Google",key="pchan"); Language=c.selectbox("Language",sorted(df.Language.unique()),key="plang")
    a,b,c=st.columns(3)
    Impressions=a.number_input("Impressions",0.0,10000000.0,50000.0,key="pimp"); Clicks=b.number_input("Clicks",0.0,1000000.0,4000.0,key="pclk"); Leads=c.number_input("Leads",0.0,1000000.0,1500.0,key="plead")
    a,b,c=st.columns(3)
    Conversions=a.number_input("Conversions",0.0,1000000.0,700.0,key="pconv"); Revenue=b.number_input("Revenue",0.0,10000000.0,300000.0,key="prev"); Acquisition_Cost=c.number_input("Acquisition Cost",0.0,1000000.0,300.0,key="pcost")
    Engagement_Score=st.number_input("Engagement Score",0.0,100.0,15.0,key="peng"); Customer_Segment=st.selectbox("Customer Segment",sorted(df.Customer_Segment.unique()),key="pseg"); Month=st.number_input("Month",1,12,6,key="pmonth"); Year=st.number_input("Year",2020,2035,2025,key="pyear")
    if st.button("Predict Profit/Loss"):
        x=pd.DataFrame([{"Brand":Brand,"Campaign_Type":Campaign_Type,"Target_Audience":Target_Audience,"Duration":Duration,"Channel_Used":Channel_Used,"Impressions":Impressions,"Clicks":Clicks,"Leads":Leads,"Conversions":Conversions,"Revenue":Revenue,"Acquisition_Cost":Acquisition_Cost,"Language":Language,"Engagement_Score":Engagement_Score,"Customer_Segment":Customer_Segment,"Month":Month,"Year":Year,"Channel_Count":len([z for z in Channel_Used.split(",") if z.strip()])}])
        pred=model.predict(x)[0]
        st.success("Predicted Result: " + ("PROFIT" if pred==1 else "LOSS"))
